### PR TITLE
adding bot_user/hello to Lighhouse config

### PR DESCRIPTION
**Pull request by zxDiscovery**

### CODE REVIEW

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[vincent-pli](https://github.com/zxDiscovery/lighthouse-config/pull/2#issuecomment-691888079 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Flighthouse-config).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zxDiscovery/lighthouse-config/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Flighthouse-config).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zxDiscovery/lighthouse-config/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by vincent-pli — CHANGES_REQUESTED** [review]
bad thing

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[vincent-pli](https://github.com/zxDiscovery/lighthouse-config/pull/2#issuecomment-691890594 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign 
You can assign the PR to them by writing `/assign ` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Flighthouse-config).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/zxDiscovery/lighthouse-config/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zxDiscovery** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[vincent-pli](https://github.com/zxDiscovery/lighthouse-config/pull/2#issuecomment-691891708 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=zxDiscovery%2Flighthouse-config).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/zxDiscovery/lighthouse-config/blob/master/OWNERS)~~ [vincent-pli]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by zxDiscovery** [comment]
@zxDiscovery: Updated the following 2 configmaps:
 * `config` configmap in namespace `lighthouse` using the following files:
   - key `config.yaml` using file `config.yaml`
 * `plugins` configmap in namespace `lighthouse` using the following files:
   - key `plugins.yaml` using file `plugins.yaml`


<details>

In response to [this](https://github.com/zxDiscovery/lighthouse-config/pull/2):

>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Pull request merged**
